name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-source:
    name: Check Source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Generate package
        run: npm pack
      - name: Upload artifact (Package)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: package
          path: '*.tgz'
      - name: prettier
        run: npm run prettier:check
      - name: eslint
        run: npm run eslint:check

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        wdio-version: ['^8.0.0', '^9.0.0']

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Force wdio version ${{ matrix.wdio-version }}
        run: |
          sed -i -e 's/"^8.0.0 || ^9.0.0"/"${{ matrix.wdio-version }}"/g' package.json
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
