name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-node-${{ matrix.node-version }}
          path: '*.tgz'
      - name: prettier
        run: npm run prettier:check
      - name: eslint
        run: npm run eslint:check
